import type {
    DefaultSharedCoreModuleContext,
    LangiumCoreServices,
    LangiumSharedCoreServices,
    Module,
    PartialLangiumCoreServices,
  } from 'langium';
  import {
    EmptyFileSystem,
    createDefaultCoreModule,
    createDefaultSharedCoreModule,
    inject,
  } from 'langium';
  import { CommonValueConverter } from '../common/valueConverter.js';
  import { MermaidGeneratedSharedModule, ActivityGeneratedModule } from '../generated/module.js';
  import { ActivityTokenBuilder } from './tokenBuilder.js';

  /**
   * declaration of "Activity" services.
   */
  interface ActivityAddedServices {
    parser: {
        TokenBuilder: ActivityTokenBuilder;
        ValueConverter: CommonValueConverter;
    };
}

    /**
     * Union of Langium default services and "activity" services.
     */
    export type ActivityServices = LangiumCoreServices & ActivityAddedServices;

    /**
     * Dependency injection module that overrides Langium default services and
    * contributes the declared `Activity` services.
    */
    export const ActivityModule: Module<ActivityServices, PartialLangiumCoreServices & ActivityAddedServices> = {
      parser: {
        TokenBuilder: () => new ActivityTokenBuilder(),
        ValueConverter: () => new CommonValueConverter(),
      },
    };

    /**
     * Create the full set of services required by Langium.
     *
     * First inject the shared services by merging two modules:
     *  - Langium default shared services
     *  - Services generated by langium-cli
     *
     * Then inject the language-specific services by merging three modules:
     *  - Langium default language-specific services
     *  - Services generated by langium-cli
     *  - Services specified in this file
     * @param context - Optional module context with the LSP connection
     * @returns An object wrapping the shared services and the language-specific services
     */
    export function createActivityServices(context: DefaultSharedCoreModuleContext = EmptyFileSystem): {
      shared: LangiumSharedCoreServices;
      Activity: ActivityServices;
    } {
      const shared: LangiumSharedCoreServices = inject(
        createDefaultSharedCoreModule(context),
        MermaidGeneratedSharedModule
      );
      const Activity: ActivityServices = inject(
        createDefaultCoreModule({ shared }),
        ActivityGeneratedModule,
        ActivityModule
      );
      shared.ServiceRegistry.register(Activity);
      return { shared, Activity };
    }



  